require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module PlanetExpress
  RSpec.describe ZoidbergsController, type: :controller do

    # This should return the minimal set of attributes required to create a valid
    # Zoidberg. As you add validations to Zoidberg, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      {name: 'Dr. John Zoidberg'}
    }

    let(:invalid_attributes) {
      {a: :b, c: :d}
    }

    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # ZoidbergsController. Be sure to keep this updated too.
    let(:valid_session) { {} }

    describe "GET index" do
      it "assigns all zoidbergs as @zoidbergs" do
        zoidberg = Zoidberg.create! valid_attributes
        get :index, {}, valid_session
        expect(assigns(:zoidbergs)).to eq([zoidberg])
      end
    end

    describe "GET show" do
      it "assigns the requested zoidberg as @zoidberg" do
        zoidberg = Zoidberg.create! valid_attributes
        get :show, {id: zoidberg.to_param}, valid_session
        expect(assigns(:zoidberg)).to eq(zoidberg)
      end
    end

    describe "GET new" do
      it "assigns a new zoidberg as @zoidberg" do
        get :new, {}, valid_session
        expect(assigns(:zoidberg)).to be_a_new(Zoidberg)
      end
    end

    describe "GET edit" do
      it "assigns the requested zoidberg as @zoidberg" do
        zoidberg = Zoidberg.create! valid_attributes
        get :edit, {id: zoidberg.to_param}, valid_session
        expect(assigns(:zoidberg)).to eq(zoidberg)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Zoidberg" do
          expect {
            post :create, {zoidberg: valid_attributes}, valid_session
          }.to change(Zoidberg, :count).by(1)
        end

        it "assigns a newly created zoidberg as @zoidberg" do
          post :create, {zoidberg: valid_attributes}, valid_session
          expect(assigns(:zoidberg)).to be_a(Zoidberg)
          expect(assigns(:zoidberg)).to be_persisted
        end

        it "redirects to the created zoidberg" do
          post :create, {zoidberg: valid_attributes}, valid_session
          expect(response).to redirect_to(Zoidberg.last)
        end
      end

      describe "with invalid params" do
        next # TODO: fix rendering
        it "assigns a newly created but unsaved zoidberg as @zoidberg" do
          post :create, {zoidberg: invalid_attributes}, valid_session
          expect(assigns(:zoidberg)).to be_a_new(Zoidberg)
        end

        it "re-renders the 'new' template" do
          post :create, {zoidberg: invalid_attributes}, valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) { valid_attributes.merge(name: 'new name') }

        it "updates the requested zoidberg" do
          zoidberg = Zoidberg.create! valid_attributes
          put :update, {id: zoidberg.to_param, zoidberg: new_attributes}, valid_session
          zoidberg.reload
          expect(zoidberg.name).to eq 'new name'
        end

        it "assigns the requested zoidberg as @zoidberg" do
          zoidberg = Zoidberg.create! valid_attributes
          put :update, {id: zoidberg.to_param, zoidberg: valid_attributes}, valid_session
          expect(assigns(:zoidberg)).to eq(zoidberg)
        end

        it "redirects to the zoidberg" do
          zoidberg = Zoidberg.create! valid_attributes
          put :update, {id: zoidberg.to_param, zoidberg: valid_attributes}, valid_session
          expect(response).to redirect_to(zoidberg)
        end
      end

      describe "with invalid params" do
        it "assigns the zoidberg as @zoidberg" do
          zoidberg = Zoidberg.create! valid_attributes
          put :update, {id: zoidberg.to_param, zoidberg: invalid_attributes}, valid_session
          expect(assigns(:zoidberg)).to eq(zoidberg)
        end

        it "re-renders the 'edit' template" do
          skip 'fix rendering'
          zoidberg = Zoidberg.create! valid_attributes
          put :update, {id: zoidberg.to_param, zoidberg: invalid_attributes}, valid_session
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested zoidberg" do
        zoidberg = Zoidberg.create! valid_attributes
        expect {
          delete :destroy, {id: zoidberg.to_param}, valid_session
        }.to change(Zoidberg, :count).by(-1)
      end

      it "redirects to the zoidbergs list" do
        zoidberg = Zoidberg.create! valid_attributes
        delete :destroy, {id: zoidberg.to_param}, valid_session
        expect(response).to redirect_to(zoidbergs_url)
      end
    end

  end
end
